---
- name: distribute motd file for centos
  template: src=cent-motd.j2
            dest=/etc/motd
            owner=root
            group=root
            mode=0644
  when: ansible_distribution == 'CentOS'
