# role:mail directory:tasks
#
- name: Mail | install postfix and dovecot
  yum: pkg={{ item }} state=installed
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 6
  with_items:
      - postfix
      - dovecot
      - cyrus-sasl-plain

- name: Mail | setup key directories
  file: path=/etc/ssl/private owner=root group=root state=directory

- name: Mail | setup mail key from ansible vault
  copy: content="{{ mail_key }}" dest=/etc/ssl/private/mail.key owner=root group=root mode=0644
  sudo: yes

- name: Mail | set up mail cert
  copy: src=mailcert.pem dest=/etc/ssl/certs/mailcert.pem owner=root group=root mode=0644
  sudo: yes

- name: Mail | setup dovecot configuration files
  copy: src=dovecot.conf dest=/etc/dovecot/dovecot.conf owner=root group=root mode=0644
  notify: restart dovecot

- name: Mail | setup postfix master.cf configuration files
  copy: src=master.cf dest=/etc/postfix/master.cf owner=root group=root mode=0644 force=yes backup=yes
  notify: restart postfix
 
- name: Mail | setup postfix main.cf configuration files
  copy: src=main.cf dest=/etc/postfix/main.cf owner=root group=root mode=0644 force=yes backup=yes
  notify: restart postfix

- name: Mail | Start up postfix
  service: name=postfix state=started enabled=yes
  tags: postfix

- name: Mail | Start up dovecot
  service: name=dovecot state=started enabled=yes
  tags: dovecot
